# Copyright 2021 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Enable Auto-TLS 
  hosts: cloudera_manager
  gather_facts: no
  roles:
    - { role: extra/patch-auto-tls, when: "cloudera_manager_version is version('7.3.0','<')" }
    - { role: extra/auto-tls, when: not use_root_ca }
    - { role: extra/auto-tls-root-ca, when: use_root_ca }
    - operations/restart_cm
    - operations/restart_agents
  tags:
    - security
    - autotls

