# Copyright 2021 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Install Cloudera Manager daemons
  hosts: cloudera_manager, cluster
  become: yes
  any_errors_fatal: true
  roles:
    - cloudera_manager/daemons

- name: Install Cloudera Manager agents
  hosts: cloudera_manager, cluster
  become: yes
  any_errors_fatal: true
  roles:
    - cloudera_manager/agent

- name: Install Cloudera Manager server
  hosts: cloudera_manager
  become: yes
  roles:
    - cloudera_manager/server

- name: Apply Cloudera Manager license
  hosts: cloudera_manager
  gather_facts: no
  roles:
    - cloudera_manager/license

- name: Configure Cloudera Manager server for TLS
  hosts: cloudera_manager
  become: yes
  gather_facts: no
  roles:
    - role: cloudera_manager/server_tls
      when: tls | default(False) or manual_tls_cert_distribution | default(False)

- name: Configure Cloudera Manager agents
  hosts: cloudera_manager, cluster
  become: yes
  any_errors_fatal: true
  roles:
    - cloudera_manager/agent_config

- name: Configure Cloudera Manager server
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - cloudera_manager/config
  vars:
    api_config_keys_uppercase: True
    api_configs: "{{ cloudera_manager_options | default({}) }}"

- name: Configure Cloudera Manager external auth
  hosts: cloudera_manager
  gather_facts: no
  roles:
    - cloudera_manager/external_auth

- name: Configure Cloudera Manager external accounts
  hosts: cloudera_manager
  gather_facts: no
  roles:
    - cloudera_manager/external_account

