# Copyright 2021 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Group hosts by whether TLS is enabled
  hosts: all
  gather_facts: no
  tasks:
    - import_tasks: tasks/group_hosts_by_tls.yml

- name: Create temp directory
  hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: Create temp dir
    file:
     path: "{{ local_temp_dir }}/"
     state: directory
     mode: 0777
     group: root
     owner: root
  tags:
    - os
    - tmp_dir

- name: Apply OS pre-requisite configurations
  hosts: cloudera_manager, cluster
  become: yes
  roles:
    - prereqs/os
  tags:
    - os

- name: Create local user accounts
  hosts: cloudera_manager, cluster, tls
  become: yes
  gather_facts: no
  roles:
    - prereqs/user_accounts
  tags:
    - users

- name: Install JDK
  hosts: cloudera_manager, cluster, tls
  become: yes
  roles:
    - prereqs/jdk
  tags:
    - jdk

- name: Install Python 3 if needed
  hosts: cloudera_manager, cluster
  become: yes
  roles:
    - prereqs/python3
  tags:
    - python

- name: Install Python 2 for KTS servers
  hosts: kts_servers
  become: yes
  roles:
    - { role: prereqs/python2 , when: encryption_activated | default('false') }
  tags:
    - python

- name: Pre-requisites on ECS Nodes for GPU
  hosts: pvc_hosts
  gather_facts: false
  roles: 
    - role: prereqs/pvc_ecs_gpu
      when: 
        - pvc_type == "ECS"
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version | int >= 8
  tags:
    - pvc