---
- name: Group hosts by whether TLS is enabled
  hosts: pvc_hosts
  gather_facts: no
  tasks:
    - import_tasks: tasks/group_hosts_by_tls.yml

- name: Apply OS pre-requisite configurations
  hosts: pvc_hosts
  become: yes
  roles:
    - role: prereqs/os
      when: pvc_type == "ECS"
  tags:
    - os

- name: Create local user accounts
  hosts: pvc_hosts
  become: yes
  gather_facts: no
  roles:
    - role: prereqs/user_accounts
      when: pvc_type == "ECS"
  tags:
    - users

- name: Install JDK
  hosts: pvc_hosts
  become: yes
  roles:
    - role: prereqs/jdk
      when: pvc_type == "ECS"
  tags:
    - jdk

- name: Install MySQL Connector
  hosts: pvc_hosts
  gather_facts: no
  become: yes
  roles:
    - role: prereqs/mysql_connector
      when: database_type == 'mysql' or database_type == 'mariadb' and pvc_type == "ECS"
  tags:
    - mysql_connector

- name: Install Oracle Connector
  hosts: pvc_hosts
  gather_facts: no
  become: yes
  roles:
    - role: prereqs/oracle_connector
      when: database_type == 'oracle' and pvc_type == "ECS"
  tags:
    - oracle_connector

- name: Install Postgres Connector
  hosts: pvc_hosts
  gather_facts: no
  become: yes
  roles:
    - role: prereqs/psql_connector
      when: database_type == 'postgresql' and pvc_type == "ECS"
  tags:
    - psql_connector

- name: Install pre-requisite packages for Kerberos
  hosts: pvc_hosts
  become: yes
  roles:
    - role: prereqs/kerberos
      when: krb5_kdc_host is defined or 'krb5_server' in groups and pvc_type == "ECS"
  tags:
    - kerberos
    - prereqs

- name: Install Cloudera Manager daemons
  hosts: pvc_hosts
  become: yes
  any_errors_fatal: true
  roles:
    - role: cloudera_manager/daemons
      when: pvc_type == "ECS"

- name: Install Cloudera Manager agents
  hosts: pvc_hosts
  become: yes
  any_errors_fatal: true
  roles:
    - role: cloudera_manager/agent
      when: pvc_type == "ECS"

- name: Configure Cloudera Manager agents
  hosts: pvc_hosts
  become: yes
  any_errors_fatal: true
  roles:
    - role: cloudera_manager/agent_config_pvc
      when: pvc_type == "ECS"

- name: Create a dns and dns-entry for ECS on all PvC servers 
  hosts: pvc_hosts
  become: yes
  roles:
    - role: prereqs/pvc_ecs_dns
      when: pvc_type == "ECS"
  tags:
    - os
    - network

- name: Apply specific pre-requisites for ECS
  hosts: pvc_hosts
  become: yes
  roles:
    - role: prereqs/pvc_ecs
      when: pvc_type == "ECS"
  tags:
    - os

- name: Enable a PvC-ECS cluster
  hosts: cloudera_manager
  gather_facts: no
  roles:
    - role: deployment/create_pvc
      when: pvc_type == "ECS"
  tags:
    - pvc

- name: Enable a PvC-OC cluster
  hosts: cloudera_manager
  gather_facts: no
  roles:
    - role: deployment/create_pvc_oc
      when: pvc_type == "OC"
  tags:
    - pvc
  