# Copyright 2021 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Restart Cluster Base
  hosts: cloudera_manager
  roles:
    - operations/restart_cluster
  tags:
    - kts
  vars:
    cluster_restart_timeout: 3600
    cluster_to_restart: "{{ cluster_name }}"

- name: Restart Cluster Stream
  hosts: cloudera_manager
  roles:
    - operations/restart_cluster
  tags:
    - kts
    - stream
  vars:
    cluster_restart_timeout: 3600
    cluster_to_restart: "{{ cluster_name }}-stream"
  ignore_errors: yes

- name: Group hosts using host template information
  hosts: all
  gather_facts: no
  tasks:
    - import_tasks: tasks/group_hosts.yml
  tags:
    - always

- name: Setup Key Trustee Server HA
  import_playbook: setup_kts_ha.yml
  when: "'kts_passive' in groups"
  tags:
    - kts

- name: Create Key Trustee Server organisation
  hosts: kts_active
  become: yes
  tasks:
    - shell: >
        keytrustee-orgtool add
        -n {{ keytrustee_server_org_name }}
        -c {{ keytrustee_server_org_email }}
        --confdir {{ keytrustee_server_conf_dir }}
  tags:
    - kts

- name: Setup KMS service
  import_playbook: setup_kms_service.yml
  when: "'kms_servers' in groups"
  tags:
    - kms

- name: Enable KMS HA
  import_playbook: setup_kms_ha.yml
  when:
    - "'kms_servers' in groups and groups.kms_servers | length > 1"
  tags:
    - kms

- name: Refresh KMS Ranger Repo
  import_playbook: refresh_ranger_kms_repo.yml
  when: "'kms_servers' in groups"
  tags:
    - kms

- name: Restart and re-deploy client configs
  hosts: cloudera_manager
  gather_facts: no
  roles:
    - operations/restart_stale
  tags:
    - restart
  vars:
    client_config_timeout: "{{ setup_hdfs_encryption_client_config_timeout | default(300) }}"
