# Copyright 2021 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Download MySQL Connector/J
  get_url:
    url: "{{ mysql_connector_url }}"
    dest: "{{ mysql_connector_download_dir }}/mysql-connector-java.zip"
    checksum: "{{ mysql_connector_checksum }}"
    mode: 0644
    validate_certs: no
  become: no
  run_once: true
  delegate_to: localhost

- name: Create /usr/share/java directory
  file:
    path: /usr/share/java
    state: directory
    mode: 0755

- name: Install unzip package
  package:
    name: unzip
    state: present

- name: Extract MySQL Connector/J zip file
  unarchive:
    src: "{{ mysql_connector_download_dir }}/mysql-connector-java.zip"
    dest: "{{ mysql_connector_extract_dir }}"
    exclude:
      - src

- name: Copy MySQL Connector/J jar file to correct location
  copy:
    src: "{{ mysql_connector_local_path }}"
    dest: /usr/share/java/mysql-connector-java.jar
    remote_src: yes
    mode: 0644

- name: Remove mariadb packages id needed
  package: 
    name: mariadb-devel
    state: absent
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"
  ignore_errors: true

- name: Install Mysql packages 
  package: 
    name: 
      - mysql
      - mysql-devel
    state: installed
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"
  ignore_errors: true

- name: Send my_config.h for RHEL 8 
  template: 
    src: my_config.h
    dest:  /usr/include/mysql/my_config.h
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"

- name: Install Mysql packages for python
  shell: pip install MySQL-python --force-reinstall --ignore-installed
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"
  ignore_errors: true

- name: Chmod on mysql python files
  shell: chmod -R 755 /usr/lib64/python2.7/site-packages/MySQLdb /usr/lib64/python2.7/site-packages/MySQL_python* /usr/lib64/python2.7/site-packages/_mysql*
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"
  ignore_errors: true
