---
- name: DEBUG Auto-TLS using password
  debug:
    msg: "{{ lookup('template', 'auto-tls.json') }}"
  when: node_password | length > 0 and debug | default(false)

- name: Enable Auto-TLS
  cm_api:
    endpoint: "/cm/commands/generateCmca"
    method: POST
    body: "{{ lookup('template', 'auto-tls.json') }}"
  ignore_errors: true
  when: node_password | length > 0

- name: Set node_key on one line
  set_fact:
    node_key_one_line: "{{ lookup('file', '~/node_key' ) | replace('\n', '\\n') | replace('\"', '\\\"' ) }}"
  when: node_key | length > 0 

- name: DEBUG Auto-TLS using key
  debug:
    msg: "{{ lookup('template', 'auto-tls-key.json') }}"
  when: node_key | length > 0 and debug | default(false)

- name: Enable Auto-TLS
  cm_api:
    endpoint: "/cm/commands/generateCmca"
    method: POST
    body: "{{ lookup('template', 'auto-tls-key.json') }}"
  ignore_errors: true
  when: node_key | length > 0