---
- name: Check if password or key is used to connect to machines
  set_fact:
    use_password: "{{ true if node_password is defined and node_password|length > 0 else false }}"

- name: DEBUG Auto-TLS using password
  debug:
    msg: "{{ lookup('template', 'auto-tls.json') }}"
  when: use_password and debug | default(false)

- name: Enable Auto-TLS
  cm_api:
    endpoint: "/cm/commands/generateCmca"
    method: POST
    body: "{{ lookup('template', 'auto-tls.json') }}"
  ignore_errors: true
  when: use_password

- name: Set node_key on one line
  set_fact:
    node_key_one_line: "{{ lookup('file', '/tmp/node_key' ) | replace('\n', '\\n') | replace('\"', '\\\"' ) }}"
  when: not use_password

- name: DEBUG Auto-TLS using key
  debug:
    msg: "{{ lookup('template', 'auto-tls-key.json') }}"
  when: not use_password

- name: Enable Auto-TLS
  cm_api:
    endpoint: "/cm/commands/generateCmca"
    method: POST
    body: "{{ lookup('template', 'auto-tls-key.json') }}"
  ignore_errors: true
  when: not use_password